# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 * * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: asset/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_limit: 12
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage


      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: asset/general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, tcl, jupyter%20notebook
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          plugin_traffic: yes
          plugin_lines: yes
          
      - name: 🦑 Followup
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: asset/followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: no
          plugin_habits_from: 1000
          plugin_habits_days: 30
          
          
      - name: 🦑 Community
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: asset/community.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""      
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
          plugin_stock: yes
          plugin_stock_token: ${{ secrets.STOCK_TOKEN }}
          plugin_stock_symbol: ACN
          plugin_stock_duration: 1d
          plugin_stock_interval: 5m
          
      - name: 🦑 People
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: asset/people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""        
          plugin_people: yes
          plugin_people_types: followers
          
